import { RiskConfig } from "./engine";

export const defaultRiskConfig: RiskConfig = {
  referenceTsMs: 0,
  windowMs: 10_000,
  historyWindowMs: 2 * 60 * 1000,
  maxPriorWindows: 12,
  minConfidence: 0.3,
  fullConfidence: 0.6,
  lowConfidenceScale: 0.05,
  partialConfidenceScale: 0.25,
  repetitionDecayExponent: 0.6,
  unknownLabelWeight: 3,
  minorLabels: ["trash", "debris", "litter", "unknown"],
  labelWeights: {
    active_fire: 58,
    flame: 45,
    smoke: 32,
    collision: 52,
    person_on_roadway: 42,
    person: 16,
    vehicle: 20,
    intrusion: 34,
    leak: 30,
    chemical_spill: 46,
    oil_sheen: 40,
    illegal_dumping: 36,
    runoff: 28,
    trash: 4,
  },
  labelCategories: {
    active_fire: "fire",
    flame: "fire",
    smoke: "fire",
    collision: "roadway",
    person_on_roadway: "roadway",
    vehicle: "roadway",
    person: "security",
    intrusion: "security",
    leak: "environmental",
    chemical_spill: "environmental",
    oil_sheen: "environmental",
    illegal_dumping: "environmental",
    runoff: "environmental",
    trash: "other",
  },
  categoryCaps: {
    fire: 70,
    environmental: 68,
    roadway: 65,
    security: 55,
    other: 28,
    unknown: 20,
  },
  persistence: {
    perOccurrenceWeight: 2.6,
    perTrackWeight: 4,
    maxPerLabel: 16,
    maxTotal: 24,
  },
  trend: {
    countIncreaseWeight: 5,
    areaIncreaseWeight: 22,
    smokeToFlameBonus: 20,
    maxTotal: 30,
  },
  regionMultipliers: {
    forest: { fire: 1.35 },
    riverbank: { environmental: 1.45 },
    intersection: { roadway: 1.25 },
    roadway: { roadway: 1.2 },
    facility: { security: 1.25, environmental: 1.15, fire: 1.15 },
    other: {},
  },
  compound: {
    personVehicleNearBonus: 16,
    personFireNearBonus: 14,
    collisionSmokeBonus: 18,
    smokeFlameBonus: 24,
    oilSheenRiverbankBonus: 16,
    proximityDistanceThreshold: 0.18,
    iouThreshold: 0.02,
    maxTotal: 45,
  },
  severityThresholds: {
    lowMax: 29,
    mediumMax: 49,
    highMax: 74,
  },
  threatThresholds: {
    lowMax: 39,
    moderateMax: 59,
    highMax: 79,
  },
  priority: {
    riskScoreWeight: 1.4,
    maxRecencyBonus: 30,
    recencyHalfLifeMs: 20 * 60 * 1000,
    escalationWeight: 0.8,
    maxEscalationBonus: 35,
    contextBonusByCategory: {
      fire: 10,
      environmental: 9,
      roadway: 8,
      security: 7,
      other: 4,
      unknown: 2,
    },
    minScore: 0,
    maxScore: 220,
  },
  maxBoostTotal: 60,
  topFactors: 8,
};

